apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs-app
  namespace: mern-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
      # annotations:
      #   # Annotation-based scraping (works with many Prometheus charts)
      #   prometheus.io/scrape: "true"
      #   prometheus.io/path: "/metrics"
      #   prometheus.io/port: "3000"
    spec:
      containers:
      - name: nodejs-app
        image: 17harsha08/nodejs-small-image
        ports:
        - containerPort: 4000
        #   name: metrics
        # readinessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 3000
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 3000
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
