apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: mern-app
spec:
  type: ClusterIP
  selector:
    app: nodejs-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
